[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  GIT_SUBMODULE_STRATEGY = "none"
  HUGO_VERSION = "0.124.1"
[[redirects]]
  from = "http://thesoderqvist.com/*"
  to = "https://thesoderqvist.com/:splat"
  status = 301
